using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace StreamerBotSkin.Models
{
  public enum SBActionTypes
  {
    Nothing,
    PlaySound,
    UdpBroadcast,
    WriteToFile,
    Action,
    ReadRandomLineFromFile,
    PerformCommand,
    PlaySoundFromFolder,
    SetTimerState,
    SetCommandState,
    Message,
    RedemptionStatus,
    SubscriberOnly,
    EmoteOnly,
    SlowMode,
    SetChannelTitle,
    SetChannelGame,
    CreateStreamMarker,
    CreateClip,
    RunCommercial,
    Timeout,
    ObsSourceVisbility,
    ObsRandomGroupSourceVisible,
    ObsHideGroupSources,
    ObsStreaming,
    ObsSetActiveScene,
    ObsSourceFilterState,
    ObsFlipSource,
    ObsRotateSource,
    ObsSetBrowserSourceUrl,
    ObsSetGdiText,
    ObsSetRandomFilterState,
    ObsHideSourceFilters,
    ObsSourceMuteState,
    ObsGetCurrentScene,
    ObsSetAudioTrackState,
    ObsRecording,
    ObsRaw,
    ObsSceneFilterState,
    ObsTakeScreenshot,
    ObsSetMediaState,
    AddTargetInfo,
    AddFollowAgeInfo,
    GetActionGroupState = 107,
    LogicIf = 120,
    GlobalGet,
    GlobalSet,
    SetArgument,
    Break,
    RewardSetEnabledState = 200,
    RewardSetPausedState,
    RewardSetCost,
    RewardConfigure,
    RewardSetCooldown,
    RewardSetTitle,
    RewardSetPrompt,
    RewardUpdate,
    ObsSetReplayBufferState = 321,
    ObsSetMediaSourceFile,
    ObsSetImageSourceFile,
    ObsGetSceneItemProperties,
    SlobsSourceVisibility,
    SlobsRandomGroupSourceVisible,
    SlobsHideGroupSources,
    SlobsStreaming,
    SlobsSetActiveScene,
    SlobsSourceFilterState,
    SlobsFlipSource,
    SlobsRotateSource,
    SlobsSetBrowserSourceUrl,
    SlobsSetGdiText,
    SlobsSetRandomFilterState,
    SlobsHideSourceFilters,
    SlobsSourceMuteState,
    SlobsGetCurrentScene,
    SlobsRecording,
    SlobsRaw,
    SlobsSceneFilterState,
    TwitchSpeakerSpeak,
    GetQuote,
    SetActionQueuePauseState,
    DelayAction,
    GetRandomNumber,
    SetActionState,
    ClearActionQueue,
    ReadLinesFromFile,
    FetchUrl,
    PickColor,
    Comment,
    SetCommandGroupState,
    SetActionGroupState,
    KeyboardPress,
    GetCommands,
    GetCommandState,
    GetCommandGroupState,
    GetActionState,
    ExecuteMethod,
    ExecuteCode
  }
}
