<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.22621.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>x64</Platforms>
  </PropertyGroup>

  <PropertyGroup Label="Avalonia">
    <AvaloniaUseCompiledBindingsByDefault>True</AvaloniaUseCompiledBindingsByDefault>
    <AvaloniaNameGeneratorDefaultFieldModifier>Public</AvaloniaNameGeneratorDefaultFieldModifier>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaXaml Remove="Menues\**" />
    <Compile Remove="Menues\**" />
    <EmbeddedResource Remove="Menues\**" />
    <None Remove="Menues\**" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaXaml Remove="UserControl1.axaml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="UserControl1.axaml.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.1.4" />
    <PackageReference Include="Avalonia.Controls.ColorPicker" Version="11.1.4" />
    <PackageReference Include="Material.Avalonia" Version="3.7.4" />
    <PackageReference Include="Material.Icons.Avalonia" Version="2.1.10" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="TextField.axaml" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="UserControl1.axaml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Fields\SensitiveTextField.axaml.cs">
      <DependentUpon>SensitiveTextField.axaml</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
